[package]
name = "libfirm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libfirm-sys = { path = "../libfirm-sys" }
paste = "1.0"
libc = "0.2.134"
tempfile = "3"
anyhow = "1.0.57"