[package]
name = "btfparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
anyhow = "1.0.57"
log = "0.4.14"
env_logger = "0.9.0"